language: go
sudo: false
go:
- tip
script:
- make travis
env:
  global:
  - secure: o1obdZ+I0NoUpWSGLFMy8csuZ1pKczoR0SO2U6nHpWwomO6bbaCAhhe02HxuRpx+usHwUCzLBkHDk5tI3A6vWbqm6TLW/ZtWdE/0XqxQdg8KLMzSrFYHh0tFTi0Y2CEieGFN1N+WY2Y79XlHh8210Q5vW/4RdVKW+YctCzj4+zBCab4ArqM+WmnXXlQcaTMMnHEhYjai25XgpMnDVi6J0ydCRe1uLm0pp4cnJ9Hb+dRDscR/sA1sb5We6Yy+GfwgmR12/V+XsLL2ei9w9iMMQ1iT9MWuAOypaMtw/iWPFWeUjpk0xRNNHMWfZOdOHkhYpIFPz+SGF3+ghrpbae+gniL6KBo466SRcKr7mfW9CL4B7YGt2bhzVV4+3kpDVwid9fmDS+C9KpHiMYzktNzqTgVkM0NTOT9p9dgN46NolyufU2sj8jz989jzG7MbgLCI8G9XfmbGAXCLty6rS4+V4u3m+r8NdH7O6n7rqMHAjlx/3w8sokteBcGBfg+D8I5GqXk0GhtOv2xiXmG9dKzdK9A2SuHmViCE2WJXtfGyUAW1o30JjIK3nC+et+a43+MBKiTh2o/S77rUzpOzbxTXWuEyc6YkvEX2pzoAfPFHOWjrxTTltBkKgAKnV1PUUJUb1i0+wKWHkuUa0sCjPCNdo49Z7kqRZAMuJ8x/AjzBCOA=
